name: chat_app_flutter
description: "Chat App made in flutter."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  cached_network_image: 3.4.1
  cookie_jar: 4.0.9
  dio: 5.10.0
  dio_cookie_manager: 3.4.0
  events_emitter: 0.6.0
  flutter:
    sdk: flutter
  http: 1.6.0
  intl: 0.20.3
  path_provider: 2.1.6
  video_player: 2.12.0
  video_player_win: 3.2.2

dev_dependencies:
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
